{
 "title": "UBS Snort Grafana",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Protocol",
   "type": "piechart",
   "description": "Shows what protocol was used on incident",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(*) FROM snort_alerts GROUP BY protocol\n"
    }
   ]
  },
  {
   "title": "Total Alerts",
   "type": "gauge",
   "description": "Shows total alerts happened",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(*) AS \"Alert Count\" \nFROM \"snort_alerts\" "
    }
   ]
  },
  {
   "title": "Timestamp Alert ",
   "type": "timeseries",
   "description": "Shows how many alerts happened during certain timestamp ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT count(*) AS \"Alert Count\"\nFROM \"snort_alerts\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(0)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Snort Log",
   "type": "table",
   "description": "Full data of snort log",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "SELECT * \nFROM \"snort_alerts\" \nWHERE time >= now() - 60d\n\n"
    }
   ]
  }
 ]
}